package com.siem.detection;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.siem.config.SiemProperties;
import com.siem.model.DnsEvent;
import com.siem.model.SecurityAlert;
import org.apache.kafka.common.serialization.Serde;
import org.apache.kafka.common.serialization.Serdes;
import org.apache.kafka.streams.StreamsBuilder;
import org.apache.kafka.streams.kstream.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.kafka.support.serializer.JsonSerde;
import org.springframework.stereotype.Component;

import java.util.Set;

/**
 * Detects Domain Generation Algorithm (DGA) domains.
 *
 * DGA domains are algorithmically generated by malware for C2 communication.
 * Detection uses heuristics:
 * - High entropy (randomness)
 * - Unusual length
 * - NXDOMAIN responses
 * - Known malicious TLDs
 *
 * MITRE ATT&CK: T1568.002 - Domain Generation Algorithms
 */
@Component
public class DgaDetector {

    private static final Logger log = LoggerFactory.getLogger(DgaDetector.class);

    // Known suspicious TLDs often used by DGA
    private static final Set<String> SUSPICIOUS_TLDS = Set.of(
            "top", "xyz", "club", "work", "date", "loan", "racing", "win",
            "bid", "stream", "download", "review", "click", "link"
    );

    private final SiemProperties properties;
    private final ObjectMapper objectMapper;

    public DgaDetector(SiemProperties properties, ObjectMapper objectMapper) {
        this.properties = properties;
        this.objectMapper = objectMapper;
    }

    @Autowired
    public void buildPipeline(StreamsBuilder streamsBuilder) {
        Serde<DnsEvent> dnsSerde = new JsonSerde<>(DnsEvent.class, objectMapper);
        Serde<SecurityAlert> alertSerde = new JsonSerde<>(SecurityAlert.class, objectMapper);

        // Read DNS events
        KStream<String, DnsEvent> dnsEvents = streamsBuilder
                .stream(
                        properties.kafka().topics().rawDnsLogs(),
                        Consumed.with(Serdes.String(), dnsSerde)
                );

        // Calculate DGA score and filter suspicious domains
        KStream<String, SecurityAlert> alerts = dnsEvents
                .mapValues((key, event) -> {
                    double dgaScore = calculateDgaScore(event);
                    return new ScoredDnsEvent(event, dgaScore);
                })
                .filter((key, scored) -> scored.score() >= 0.7)  // High confidence threshold
                .mapValues((key, scored) -> {
                    log.warn("DGA DETECTED: domain={} score={} from={}",
                            scored.event().queryName(),
                            scored.score(),
                            scored.event().sourceIp());

                    return SecurityAlert.dgaDetected(
                            scored.event().sourceIp(),
                            scored.event().queryName(),
                            scored.score()
                    );
                })
                .selectKey((key, alert) -> alert.alertId());

        // Output alerts
        alerts.to(
                properties.kafka().topics().alerts(),
                Produced.with(Serdes.String(), alertSerde)
        );

        log.info("DGA detection pipeline built");
    }

    /**
     * Calculate DGA probability score based on domain characteristics.
     * Returns value between 0.0 (legitimate) and 1.0 (likely DGA).
     */
    private double calculateDgaScore(DnsEvent event) {
        String domain = event.queryName();
        if (domain == null || domain.isEmpty()) return 0.0;

        double score = 0.0;

        // Extract domain parts
        String[] parts = domain.split("\\.");
        if (parts.length < 2) return 0.0;

        String secondLevelDomain = parts[parts.length - 2];
        String tld = parts[parts.length - 1];

        // Factor 1: Length of second-level domain (DGA domains often long)
        if (secondLevelDomain.length() > 15) {
            score += 0.2;
        } else if (secondLevelDomain.length() > 20) {
            score += 0.3;
        }

        // Factor 2: Entropy (randomness) of the domain
        double entropy = calculateEntropy(secondLevelDomain);
        if (entropy > 3.5) {
            score += 0.25;
        }
        if (entropy > 4.0) {
            score += 0.15;
        }

        // Factor 3: Consonant-to-vowel ratio (DGA often has unusual patterns)
        double consonantRatio = calculateConsonantRatio(secondLevelDomain);
        if (consonantRatio > 0.8 || consonantRatio < 0.2) {
            score += 0.15;
        }

        // Factor 4: Suspicious TLD
        if (SUSPICIOUS_TLDS.contains(tld.toLowerCase())) {
            score += 0.15;
        }

        // Factor 5: NXDOMAIN response (many DGA domains don't exist)
        if ("NXDOMAIN".equals(event.responseCode())) {
            score += 0.2;
        }

        // Factor 6: Numeric characters (DGA often has random numbers)
        long digitCount = secondLevelDomain.chars().filter(Character::isDigit).count();
        if (digitCount > secondLevelDomain.length() * 0.3) {
            score += 0.15;
        }

        // Factor 7: If already flagged as threat by upstream
        if (event.isThreat()) {
            score += 0.3;
        }

        return Math.min(score, 1.0);
    }

    /**
     * Calculate Shannon entropy of a string.
     * Higher entropy = more randomness = more likely DGA.
     */
    private double calculateEntropy(String str) {
        if (str == null || str.isEmpty()) return 0.0;

        int[] freq = new int[256];
        for (char c : str.toLowerCase().toCharArray()) {
            freq[c]++;
        }

        double entropy = 0.0;
        int length = str.length();

        for (int f : freq) {
            if (f > 0) {
                double p = (double) f / length;
                entropy -= p * (Math.log(p) / Math.log(2));
            }
        }

        return entropy;
    }

    /**
     * Calculate ratio of consonants to total letters.
     */
    private double calculateConsonantRatio(String str) {
        if (str == null || str.isEmpty()) return 0.5;

        String vowels = "aeiouAEIOU";
        long letterCount = str.chars().filter(Character::isLetter).count();
        if (letterCount == 0) return 0.5;

        long vowelCount = str.chars().filter(c -> vowels.indexOf(c) >= 0).count();
        return 1.0 - ((double) vowelCount / letterCount);
    }

    private record ScoredDnsEvent(DnsEvent event, double score) {}
}
