package com.siem.model;

import java.time.Instant;
import java.util.List;
import java.util.Map;
import java.util.UUID;

/**
 * Security alert generated by detection rules.
 * This is the output of the threat detection pipeline.
 */
public record SecurityAlert(
    String alertId,
    Instant timestamp,
    Instant detectedAt,

    // Classification
    AlertType type,
    SecurityEvent.Severity severity,
    String ruleName,
    String ruleId,
    double confidenceScore,

    // Context
    String title,
    String description,
    List<String> relatedEventIds,
    String sourceIp,
    String destinationIp,
    String userId,
    String hostname,

    // MITRE ATT&CK mapping
    String mitreTactic,
    String mitreTechnique,

    // Response
    AlertStatus status,
    String assignee,
    Instant acknowledgedAt,
    Instant resolvedAt,
    String resolution,

    // Metadata
    Map<String, Object> evidence
) {
    public enum AlertType {
        BRUTE_FORCE,
        PORT_SCAN,
        DATA_EXFILTRATION,
        MALWARE_COMMUNICATION,
        PRIVILEGE_ESCALATION,
        LATERAL_MOVEMENT,
        CREDENTIAL_THEFT,
        DNS_TUNNELING,
        DGA_DETECTED,
        POLICY_VIOLATION,
        ANOMALY,
        CORRELATION
    }

    public enum AlertStatus {
        NEW,
        ACKNOWLEDGED,
        INVESTIGATING,
        ESCALATED,
        RESOLVED,
        FALSE_POSITIVE,
        SUPPRESSED
    }

    // Factory methods for common alert types
    public static SecurityAlert bruteForce(String sourceIp, String targetUser, int attempts) {
        return new SecurityAlert(
            UUID.randomUUID().toString(),
            Instant.now(),
            Instant.now(),
            AlertType.BRUTE_FORCE,
            SecurityEvent.Severity.HIGH,
            "brute_force_detection",
            "RULE-001",
            0.95,
            "Brute Force Attack Detected",
            String.format("Multiple failed login attempts (%d) from %s targeting user %s",
                attempts, sourceIp, targetUser),
            List.of(),
            sourceIp,
            null,
            targetUser,
            null,
            "Credential Access",
            "T1110 - Brute Force",
            AlertStatus.NEW,
            null,
            null,
            null,
            null,
            Map.of("attempts", attempts, "source_ip", sourceIp, "target_user", targetUser)
        );
    }

    public static SecurityAlert portScan(String sourceIp, String targetIp, int portCount) {
        return new SecurityAlert(
            UUID.randomUUID().toString(),
            Instant.now(),
            Instant.now(),
            AlertType.PORT_SCAN,
            SecurityEvent.Severity.MEDIUM,
            "port_scan_detection",
            "RULE-002",
            0.85,
            "Port Scan Detected",
            String.format("Host %s scanned %d ports on %s", sourceIp, portCount, targetIp),
            List.of(),
            sourceIp,
            targetIp,
            null,
            null,
            "Reconnaissance",
            "T1046 - Network Service Scanning",
            AlertStatus.NEW,
            null,
            null,
            null,
            null,
            Map.of("port_count", portCount, "source_ip", sourceIp, "target_ip", targetIp)
        );
    }

    public static SecurityAlert dataExfiltration(String sourceIp, String destIp, long bytes) {
        return new SecurityAlert(
            UUID.randomUUID().toString(),
            Instant.now(),
            Instant.now(),
            AlertType.DATA_EXFILTRATION,
            SecurityEvent.Severity.CRITICAL,
            "data_exfiltration_detection",
            "RULE-003",
            0.90,
            "Potential Data Exfiltration",
            String.format("Large outbound data transfer (%d MB) from %s to %s",
                bytes / (1024 * 1024), sourceIp, destIp),
            List.of(),
            sourceIp,
            destIp,
            null,
            null,
            "Exfiltration",
            "T1041 - Exfiltration Over C2 Channel",
            AlertStatus.NEW,
            null,
            null,
            null,
            null,
            Map.of("bytes_transferred", bytes, "source_ip", sourceIp, "destination_ip", destIp)
        );
    }

    public static SecurityAlert dgaDetected(String sourceIp, String domain, double score) {
        return new SecurityAlert(
            UUID.randomUUID().toString(),
            Instant.now(),
            Instant.now(),
            AlertType.DGA_DETECTED,
            SecurityEvent.Severity.HIGH,
            "dga_detection",
            "RULE-004",
            score,
            "DGA Domain Detected",
            String.format("Suspicious domain %s queried by %s (DGA score: %.2f)",
                domain, sourceIp, score),
            List.of(),
            sourceIp,
            null,
            null,
            null,
            "Command and Control",
            "T1568.002 - Domain Generation Algorithms",
            AlertStatus.NEW,
            null,
            null,
            null,
            null,
            Map.of("domain", domain, "dga_score", score, "source_ip", sourceIp)
        );
    }
}
